updated

diff --git a/.github/workflows/sast.yml b/.github/workflows/sast.yml
--- a/.github/workflows/sast.yml
+++ b/.github/workflows/sast.yml
@@ -1,5 +1,4 @@
-name: Accuknox SAST
-
+name: Accuknox SAST + DAST Scan
 on:
   push:
     branches:
@@ -9,7 +8,7 @@ on:
       - main
 
 jobs:
-  accuknox-cicd:
+  sast:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -23,3 +22,52 @@ jobs:
           accuknox_token: "${{ secrets.AK_TOKEN }}"
           accuknox_label: "SAST"
           input_soft_fail: "true"
+
+
+  dast:
+    runs-on: ubuntu-latest
+    needs: sast
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.9'
+
+      - name: Install dependencies
+        run: |
+          pip install -r requirements.txt
+
+      - name: Start the app in background
+        run: |
+          python3 app.py &
+          echo "Waiting for the app to start..."
+          sleep 10
+
+      - name: Create output folder for ZAP reports
+        run: mkdir zap-output
+      
+      - name: Run ZAP scan
+        run: |
+          docker run --network host --rm --user 0 -v ${{ github.workspace }}/zap-output:/zap/wrk/output \
+            -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
+            -t http://localhost:5000 \
+            -J output/zap_report.json || true
+
+      - name: Sending Json to AccuKnox Console
+        run: |
+          curl -v --location --request POST "https://cspm.demo.accuknox.com/api/v1/artifact/?tenant_id=${{ secrets.AK_TENANT_ID }}&data_type=ZAP&label_id=dastgithub&save_to_s3=true" \
+          --header "Tenant-Id: ${{ secrets.AK_TENANT_ID }}" \
+          --header "Authorization: Bearer ${{ secrets.AK_TOKEN }}" \
+          --form "file=@zap-output/zap_report.json"
+      
+      - name: Check severity level and exit if high severity issues found
+        run: |
+          if grep -q '"riskCode":"High"' zap-output/zap_report.json; then
+            echo "High severity issues found in ZAP scan. Failing the job."
+            exit 1
+          else
+            echo "No high severity issues found."
+          fi
